@extends('layouts.app')

@section('title', 'Page Title')
@section('body_class', 'welcome')

@section('sidebar')
    @parent
@endsection

@section('content')
    <div id="index-banner" class="parallax-container valign-wrapper">
        <div class="section no-pad-bot">

            <div class="row center">

            </div>

        </div>
        <div class="parallax"><img src="img/header_2.png" alt="Unsplashed background img 1"></div>
    </div>

    <div class="container">
        <div class="section scrollspy" id="imprint">

            <div class="row ">

                <div class="col s12 ">
                    <h4 class="center"><i class=" red-text text-darken-4">Impressum</i></h4>
                    <h6 class="">Anbieterinformationen</h6>
                    <p class="left-align light  ">

                    Jingjing Asia Restaurant<br />
                    Gesch&auml;ftsf&uuml;hrer: Ming Yang<br />
                    Atrium Ebene 5 West Fernbahnhof<br />
                    THE SQUAIRE 13 AM FLUGHAFEN<br />
                    60549 Frankfurt am Main<br />
                    Deutschland
                    </p>

                    <p>

                        Telefon:  	+49(0)69/643 552 272<br />
                        Fax:  	+49(0)69/643 552 369<br />
                        Website:  	www.jingjing-asia.de<br />
                        Email:  	jingjing-asia@live.com

                    </p>
                    <p>
                        Vertretungsberechtigt: Jingjing Asia Restaurant<br />
                        USt.ID.nr. gem&auml;&szlig; &sect; 27 a Umsatzsteuergesetz: DE 04523665545<br />
                        Registergericht: Amtsgericht Frankfurt am Main HRA 89749<br />
                        Inhaltlich Verantwortlicher gem&auml;&szlig; TMG: Jingjing Asia Restaurant
                    </p>

                    <h5>Allgemeine Nutzungsbedingungen f&uuml;r Jingjing Asia Restaurant</h5>
                    <p><strong>1. Informationen zum Urheberrecht</strong><br />Alle Informationen dieser Web-Seite werden wie angegeben ohne Anspruch auf Richtigkeit, Vollst&auml;ndigkeit oder Aktualit&auml;t zur Verf&uuml;gung gestellt.<br />Wenn nicht ausdr&uuml;cklich anderweitig in dieser Publikation zu verstehen gegeben, und zwar in Zusammenhang mit einem bestimmten Ausschnitt, einer Datei, oder einem Dokument, ist jedermann dazu berechtigt, dieses Dokument anzusehen, zu kopieren, zu drucken und zu verteilen, unter den folgenden Bedingungen:<br />Das Dokument darf nur f&uuml;r nichtkommerzielle Informationszwecke genutzt werden. Jede Kopie dieses Dokuments oder eines Teils davon muss diese urheberrechtliche Erkl&auml;rung und das urheberrechtliche Schutzzeichen des Betreibers enthalten. Das Dokument, jede Kopie des Dokuments oder eines Teils davon d&uuml;rfen nicht ohne schriftliche Zustimmung des Betreibers ver&auml;ndert werden. Der Betreiber beh&auml;lt sich das Recht vor, diese Genehmigung jederzeit zu widerrufen, und jede Nutzung muss sofort eingestellt werden, sobald eine schriftliche Bekanntmachung seitens des Betreibers ver&ouml;ffentlicht wird.</p>
                    <p><strong>2. Vertragliche Zusicherungen und Verzichterkl&auml;rungen</strong><br />Die Website Jingjing Asia Restaurant steht Ihnen - soweit nicht anders vereinbart - kostenlos zur Verf&uuml;gung. Die Betreiber &uuml;bernehmen keinerlei Gew&auml;hr f&uuml;r Richtigkeit der enthaltenen Informationen, Verf&uuml;gbarkeit der Dienste, Verlust von auf Jingjing Asia Restaurant abgespeicherten Daten oder Nutzbarkeit f&uuml;r irgendeinen bestimmten Zweck.<br />Die Betreiber haften auch nicht f&uuml;r Folgesch&auml;den, die auf einer Nutzung des Angebotes beruhen.&nbsp;<br />Soweit ein Haftungsausschluss nicht in Betracht kommt, haften die Betreiber lediglich f&uuml;r grobe Fahrl&auml;ssigkeit und Vorsatz. Produkt- und Firmennamen sind Marken der jeweiligen Eigent&uuml;mer und werden auf diesen Seiten ausschlie&szlig;lich zu Informationszwecken eingesetzt.&nbsp;<br />Diese Publikation k&ouml;nnte technische oder andere Ungenauigkeiten enthalten oder Schreib-/Tippfehler. Von Zeit zu Zeit werden der vorliegenden Information &Auml;nderungen hinzugef&uuml;gt; diese &Auml;nderungen werden in neuen Ausgaben der Publikation eingef&uuml;gt. Der Betreiber kann jederzeit Verbesserungen und/oder Ver&auml;nderungen an den Angeboten vornehmen, die in dieser Publikation beschrieben werden.</p>
                    <p><strong>3. Meinungs&auml;u&szlig;erungen bei Kommentaren und im Forum</strong><br />Aufgrund der sich st&auml;ndig ver&auml;ndernden Inhalte bei Kommentaren und im Forum ist es dem Betreiber nicht m&ouml;glich, alle Beitr&auml;ge l&uuml;ckenlos zu sichten, inhaltlich zu pr&uuml;fen und die unmittelbare aktive Kontrolle dar&uuml;ber auszu&uuml;ben. Es wird keine Verantwortung f&uuml;r den Inhalt, die Korrektheit und die Form der eingestellten Beitr&auml;ge &uuml;bernommen.</p>
                    <p><strong>3a. Spezielle Bestimmungen f&uuml;r angemeldete Nutzer</strong><br />Mit der Anmeldung bei Jingjing Asia Restaurant erkl&auml;rt sich der Nutzer - nachfolgend &raquo;Mitglied&laquo; gegen&uuml;ber dem Betreiber mit folgenden Nutzungsbedingungen einverstanden:<br />Mitglieder, die sich an Diskussionsforen und Kommentaren beteiligen, verpflichten sich dazu,</p>
                    <ul>
                        <li>1. Sich in Ihren Beitr&auml;gen jeglicher Beleidigungen, strafbarer Inhalte, Pornographie und grober Ausdrucksweise zu enthalten,</li>
                        <li>2. Die alleinige Verantwortung f&uuml;r die von ihnen eingestellten Inhalte zu tragen, Rechte Dritter (insbesondere Marken-, Urheber- und Pers&ouml;nlichkeitsrechte) nicht zu verletzen und die Betreiber von &raquo;Jingjing Asia Restaurant&laquo; von durch ihre Beitr&auml;ge ausgel&ouml;sten Anspr&uuml;chen Dritter vollst&auml;ndig freizustellen.</li>
                        <li>3. Weder in Foren noch in Kommentaren Werbung irgendwelcher Art einzustellen oder Foren und Kommentare zu irgendeiner Art gewerblicher T&auml;tigkeit zu nutzen. Insbesondere gilt das f&uuml;r die Ver&ouml;ffentlichung von &raquo;0900&laquo;-Rufnummern zu irgendeinem Zweck.</li>
                    </ul>
                    <p>Es besteht keinerlei Anspruch auf Ver&ouml;ffentlichung von eingereichten Kommentaren oder Forenbeitr&auml;gen. Die Betreiber von &raquo;Jingjing Asia Restaurant&laquo; behalten sich vor, Kommentare und Forenbeitr&auml;ge nach eigenem Ermessen zu editieren oder zu l&ouml;schen. Bei Verletzungen der Pflichten unter 1), 2) und 3) behalten sich die Betreiber ferner vor, die Mitgliedschaft zeitlich begrenzt zu sperren oder dauernd zu l&ouml;schen.</p>
                    <p><strong>4. Einreichen von Beitr&auml;gen und Artikeln</strong><br />Soweit das Mitglied von der M&ouml;glichkeit Gebrauch macht, eigene Beitr&auml;ge f&uuml;r redaktionellen Teil von &raquo;Jingjing Asia Restaurant&laquo; einzureichen, gilt Folgendes:<br />Voraussetzung f&uuml;r das Posten eigener Beitr&auml;ge ist, dass das Mitglied seinen vollst&auml;ndigen und korrekten Vor- und Nachnamen in sein &raquo;Jingjing Asia Restaurant&laquo; - Benutzerprofil eingetragen hat oder nach dem Einreichen des Artikels dort eintr&auml;gt. Mit dem dort eingetragenen Namen wird der eingereichte Beitrag bei Ver&ouml;ffentlichung (&ouml;ffentlich) gekennzeichnet.<br />Das Mitglied gibt f&uuml;r alle Beitr&auml;ge, die von ihm oder ihr zuk&uuml;nftig auf &raquo;Jingjing Asia Restaurant&laquo; eingereicht werden, folgende Erkl&auml;rungen ab:</p>
                    <ul>
                        <li>1. Das Mitglied versichert, das die eingereichten Beitr&auml;ge frei von Rechten Dritter, insbesondere Urheber-, Marken- oder Pers&ouml;nlichkeitsrechten sind. Dies gilt f&uuml;r alle eingereichten Beitr&auml;ge und Bildwerke.</li>
                        <li>2. Das Mitglied r&auml;umt den Betreibern von &raquo;Jingjing Asia Restaurant&laquo; ein uneingeschr&auml;nktes Nutzungsrecht an den eingereichten Beitr&auml;gen ein. Dieses umfasst die Ver&ouml;ffentlichung im Internet auf &raquo;Jingjing Asia Restaurant&laquo; sowie auf anderen Internetservern, in Newslettern, Printmedien und anderen Publikationen.</li>
                        <li>3. Eingereichte Beitr&auml;ge werden auf Verlangen des Mitgliedes per Email an die Adresse des&nbsp;Webmasters&nbsp;wieder gel&ouml;scht bzw. anonymisiert. Die L&ouml;schung bzw. Anonymisierung erfolgt innerhalb von 7 Tagen nach der Mitteilung. F&uuml;r Folgesch&auml;den, die dem Mitglied aus der versp&auml;teten L&ouml;schung des Beitrages entstehen haften die Betreiber nur insoweit, als sie nicht auf einer Pflichtverletzung des Mitgliedes (oben unter 1), 2) und 3) ) und soweit sie dar&uuml;ber hinaus auf grobem Verschulden oder Vorsatz der Betreiber von &raquo;Jingjing Asia Restaurant&laquo; beruhen. Wir weisen in diesem Zusammenhang ausdr&uuml;cklich darauf hin, dass &raquo;Jingjing Asia Restaurant&laquo; regelm&auml;&szlig;ig von Suchmaschinen indexiert wird, und dass wir keinen Einfluss darauf haben, ob, wo und wie lange bei uns ver&ouml;ffentlichte Beitr&auml;ge m&ouml;glicherweise auch nach L&ouml;schung bei &raquo;Jingjing Asia Restaurant&laquo; in Datenbanken von Suchmaschinen und Webkatalogen gespeichert werden und abrufbar sind.</li>
                        <li>4. Es besteht keinerlei Anspruch auf Speicherung, Ver&ouml;ffentlichung oder Archivierung der eingereichten Beitr&auml;ge. Die Betreiber behalten sich vor, eingereichte Beitr&auml;ge ohne Angabe von Gr&uuml;nden nicht zu ver&ouml;ffentlichen, vor Ver&ouml;ffentlichung zu editieren oder nach Ver&ouml;ffentlichung nach freiem Ermessen wieder zu l&ouml;schen.</li>
                        <li>5. Durch die Ver&ouml;ffentlichung eingereichter Beitr&auml;ge entstehen keinerlei Verg&uuml;tungsanspr&uuml;che (Honorare, Lizenzgeb&uuml;hren, Aufwendungsentsch&auml;digungen oder &auml;hnliches) des Mitgliedes gegen&uuml;ber &raquo;Jingjing Asia Restaurant&laquo;. Die Mitarbeit ist ehrenamtlich (unentgeltlich).</li>
                    </ul>
                    <p><strong>5. Erkl&auml;rung zum Datenschutz (Privacy Policy)</strong><br />Sofern innerhalb des Internetangebotes die M&ouml;glichkeit zur Eingabe pers&ouml;nlicher oder gesch&auml;ftlicher Daten genutzt wird, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdr&uuml;cklich freiwilliger Basis. Die Inanspruchnahme unseres Dienstes ist - soweit technisch m&ouml;glich und zumutbar - auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet. Weitere wichtige Informationen zum Thema Datenschutz finden sich in unserer&nbsp; Erkl&auml;rung zum Datenschutz (Privacy Policy).</p>
                    <p><strong>6. Registrierung und Passwort</strong><br />Der Benutzer ist verpflichtet, die Kombination Benutzername/Passwort vertraulich zu behandeln und nicht an Dritte weiterzugeben. Bei Verdacht auf Missbrauch der Zugangsdaten ist der Betreiber zu informieren.</p>
                    <p><strong>7. Hinweis gem&auml;&szlig; Teledienstgesetz</strong><br />F&uuml;r Internetseiten Dritter, auf die die dieses Angebot durch sog. Links verweist, tragen die jeweiligen Anbieter die Verantwortung. Der Betreiber ist f&uuml;r den Inhalt solcher Seiten Dritter nicht verantwortlich. Des Weiteren kann die Web-Seite ohne unser Wissen von anderen Seiten mittels sog. Links angelinkt werden. Der Betreiber &uuml;bernimmt keine Verantwortung f&uuml;r Darstellungen, Inhalt oder irgendeine Verbindung zu dieser Web-Seite in Web-Seiten Dritter. F&uuml;r fremde Inhalte ist der Betreiber nur dann verantwortlich, wenn von ihnen (d.h. auch von einem rechtswidrigen oder strafbaren Inhalt) positive Kenntnis vorliegt und es technisch m&ouml;glich und zumutbar ist, deren Nutzung zu verhindern. Der Betreiber ist nach dem Teledienstgesetz jedoch nicht verpflichtet, die fremden Inhalte st&auml;ndig zu &uuml;berpr&uuml;fen.</p>
                    <p><strong>Kontakt</strong><br />Fragen rund um Jingjing Asia Restaurant bitte an den&nbsp; Webmaster &nbsp;richten.</p>
                    <p><strong>Rechtswirksamkeit</strong><br />Diese Allgemeinen Nutzungsbedingungen beziehen sich auf Jingjing Asia Restaurant.<br />Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollst&auml;ndig entsprechen sollten, bleiben die &uuml;brigen Teile des Dokumentes in ihrem Inhalt und ihrer G&uuml;ltigkeit davon unber&uuml;hrt.</p>



                            <h5>Erkl&auml;rung zum Datenschutz f&uuml;r Jingjing Asia Restaurant</h5>

                                <p><strong>Vorwort</strong><br />Wir nehmen den Schutz Ihrer privaten Daten ernst. Die besondere Beachtung der Privatsph&auml;re bei der Verarbeitung pers&ouml;nlicher Daten ist uns ein wichtiges Anliegen. Pers&ouml;nliche Daten werden gem&auml;ss den Bestimmungen des Bundesdatensschutzgesetzes BDSG verwendet. Die Betreiber dieser Website verpflichten sich zur Verschwiegenheit. Diese Webseiten k&ouml;nnen Links zu Webseiten anderer Anbieter enthalten, auf die sich diese Datenschutzerkl&auml;rung nicht erstreckt. Weitere wichtige Informationen finden sich auch in den&nbsp;Allgemeinen Nutzungsbedingungen.</p>
                                <p><strong>Personenbezogene Daten</strong><br />Personenbezogene Daten sind Informationen, die dazu genutzt werden k&ouml;nnen, die Identit&auml;t zu erfahren. Darunter fallen Informationen wie richtiger Name, Adresse, Postanschrift, Telefonnummer. Informationen, die nicht direkt mit der wirklichen Identit&auml;t in Verbindung gebracht werden (wie zum Beispiel favorisierte Webseiten oder Anzahl der Nutzer einer Site) fallen nicht darunter.<br />Man kann unser Online-Angebot grunds&auml;tzlich ohne Offenlegung der Identit&auml;t nutzen. Wenn man sich f&uuml;r eine Registrierung entscheidet, sich also als Mitglied (registrierter Benutzer) anmeldet, kann man im individuellen Benutzerprofil pers&ouml;nlichen Informationen hinterlegen. Es unterliegt der freien Entscheidung, ob diese Daten eingegeben werden. Da versucht wird, f&uuml;r eine Nutzung des Angebots so wenig wie m&ouml;glich personenbezogene Daten zu erheben, reicht f&uuml;r eine Registrierung die Angabe eines Namens - unter dem man als Mitglied gef&uuml;hrt wird und der nicht mit dem realen Namen &uuml;bereinstimmen muss - und die Angabe der E-Mail-Adresse, an die das Kennwort geschickt wird, aus. In Verbindung mit dem Zugriff auf unsere Seiten werden serverseitig Daten (zum Beispiel IP-Adresse, Datum, Uhrzeit und betrachtete Seiten) gespeichert. Es findet keine personenbezogene Verwertung statt. Die statistische Auswertung anonymisierter Datens&auml;tze bleibt vorbehalten.<br />Wir nutzen die pers&ouml;nlichen Daten zu Zwecken der technischen Administration der Webseiten und zur Kundenverwaltung nur im jeweils daf&uuml;r erforderlichen Umfang. Dar&uuml;ber hinaus werden pers&ouml;nliche Daten nur dann gespeichert, wenn diese freiwillig angegeben werden.</p>
                                <p><strong>Weitergabe personenbezogener Daten</strong><br />Wir verwenden personenbezogene Informationen nur f&uuml;r diese Webseite. Wir geben die Informationen nicht ohne ausdr&uuml;ckliches Einverst&auml;ndnis an Dritte weiter. Sollten im Rahmen der Auftragsdatenverarbeitung Daten an Dienstleister weitergegeben werden, so sind diese an das Bundesdatenschutzgesetz BDSG, andere gesetzliche Vorschriften und an diese Privacy Policy gebunden.<br />Erhebungen beziehungsweise &uuml;bermittlungen pers&ouml;nlicher Daten an staatliche Einrichtungen und Beh&ouml;rden erfolgen nur im Rahmen zwingender Rechtsvorschriften.</p>
                                <p><strong>Einsatz von Cookies</strong><br />Wir setzen Cookies - kleine Dateien mit Konfigurationsinformationen - ein. Sie helfen dabei, benutzerindividuelle Einstellungen zu ermitteln und spezielle Benutzerfunktionen zu realisieren. Wir erfassen keine personenbezogenen Daten &uuml;ber Cookies. S&auml;mtliche Funktionen der Website sind auch ohne Cookies einsetzbar, einige benutzerdefinierte Eigenschaften und Einstellungen sind dann allerdings nicht verf&uuml;gbar.</p>
                                <p><strong>Kinder</strong><br />Personen unter 18 Jahren sollten ohne Zustimmung der Eltern oder Erziehungsberechtigten keine personenbezogenen Daten an uns &uuml;bermitteln. Wir fordern keine personenbezogenen Daten von Kindern an, sammeln diese nicht und geben sie nicht an Dritte weiter.</p>
                                <p><strong>Recht auf Widerruf</strong><br />Wenn Sie uns personenbezogene Daten &uuml;berlassen haben, k&ouml;nnen Sie diese jederzeit im Benutzerprofil wieder &auml;ndern und l&ouml;schen. F&uuml;r eine vollst&auml;ndige L&ouml;schung des Accounts bitte an den&nbsp;Webmaster&nbsp;wenden. Bis zu diesem Zeitpunkt erfolgte Beitr&auml;ge in Foren, Kommentaren, Terminank&uuml;ndigungen und Artikeln bleiben allerdings unter Umst&auml;nden erhalten - Informationen dazu auch bei den&nbsp; allgemeinen Nutzungsbedingungen.</p>
                                <p><strong>Links zu anderen Websites</strong><br />Unser Online-Angebot enth&auml;lt Links zu anderen Websites. Wir haben keinen Einfluss darauf, dass deren Betreiber die Datenschutzbestimmungen einhalten.</p>
                                <p><strong>Beitr&auml;ge</strong><br />Die Beitr&auml;ge auf unserer Seite sind f&uuml;r jeden zug&auml;nglich. Beitr&auml;ge sollten vor der Ver&ouml;ffentlichung sorgf&auml;ltig darauf &uuml;berpr&uuml;ft werden, ob sie Angaben enthalten, die nicht f&uuml;r die &Ouml;ffentlichkeit bestimmt sind. Die Beitr&auml;ge werden m&ouml;glicherweise in Suchmaschinen erfasst und auch ohne gezielten Aufruf dieser Website weltweit zugreifbar.</p>
                                <p><strong>Fragen und Kommentare</strong><br />Bei Fragen und f&uuml;r Anregungen und Kommentare zum Thema Datenschutz bitte per Mail an den&nbsp; Webmaster &nbsp;von Jingjing Asia Restaurant wenden.</p>
                                <p><strong>Auskunftsrecht</strong><br />Sie haben jederzeit das Recht auf Auskunft &uuml;ber die bez&uuml;glich Ihrer Person gespeicherten Daten, deren Herkunft und Empf&auml;nger sowie den Zweck der Datenverarbeitung. Auskunft &uuml;ber die gespeicherten Daten gibt der&nbsp;Webmaster.</p>
                                <p><strong>Sicherheitshinweis:</strong><br />Wir sind bem&uuml;ht Ihre personenbezogenen Daten durch Ergreifung aller technischen und organisatorischen M&ouml;glichkeiten so zu speichern, dass sie f&uuml;r Dritte nicht zug&auml;nglich sind. Bei der Kommunikation per E Mail kann die vollst&auml;ndige Datensicherheit von uns nicht gew&auml;hrleistet werden, so dass wir Ihnen bei vertraulichen Informationen den Postweg empfehlen.</p>



                            <h5>Haftungsausschluss (Disclaimer) f&uuml;r Jingjing Asia Restaurant</h5>

                                <p><strong>1. Inhalt des Onlineangebotes</strong><br />Der Autor &uuml;bernimmt keinerlei Gew&auml;hr f&uuml;r die Aktualit&auml;t, Korrektheit, Vollst&auml;ndigkeit oder Qualit&auml;t der bereitgestellten Informationen. Haftungsanspr&uuml;che gegen den Autor, welche sich auf Sch&auml;den materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollst&auml;ndiger Informationen verursacht wurden, sind grunds&auml;tzlich ausgeschlossen, sofern seitens des Autors kein nachweislich vors&auml;tzliches oder grob fahrl&auml;ssiges Verschulden vorliegt.&nbsp;<br />Alle Angebote sind freibleibend und unverbindlich. Der Autor beh&auml;lt es sich ausdr&uuml;cklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ank&uuml;ndigung zu ver&auml;ndern, zu erg&auml;nzen, zu l&ouml;schen oder die Ver&ouml;ffentlichung zeitweise oder endg&uuml;ltig einzustellen.</p>
                                <p><strong>2. Verweise und Links</strong><br />Bei direkten oder indirekten Verweisen auf fremde Webseiten ("Hyperlinks"), die au&szlig;erhalb des Verantwortungsbereiches des Autors liegen, w&uuml;rde eine Haftungsverpflichtung ausschlie&szlig;lich in dem Fall in Kraft treten, in dem der Autor von den Inhalten Kenntnis hat und es ihm technisch m&ouml;glich und zumutbar w&auml;re, die Nutzung im Falle rechtswidriger Inhalte zu verhindern.&nbsp;<br />Der Autor erkl&auml;rt hiermit ausdr&uuml;cklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zuk&uuml;nftige Gestaltung, die Inhalte oder die Urheberschaft der verlinkten/verkn&uuml;pften Seiten hat der Autor keinerlei Einfluss. Deshalb distanziert er sich hiermit ausdr&uuml;cklich von allen Inhalten aller verlinkten /verkn&uuml;pften Seiten, die nach der Linksetzung ver&auml;ndert wurden. Diese Feststellung gilt f&uuml;r alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie f&uuml;r Fremdeintr&auml;ge in vom Autor eingerichteten G&auml;steb&uuml;chern, Diskussionsforen, Linkverzeichnissen, Mailinglisten und in allen anderen Formen von Datenbanken, auf deren Inhalt externe Schreibzugriffe m&ouml;glich sind. F&uuml;r illegale, fehlerhafte oder unvollst&auml;ndige Inhalte und insbesondere f&uuml;r Sch&auml;den, die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der &uuml;ber Links auf die jeweilige Ver&ouml;ffentlichung lediglich verweist.</p>
                                <p><strong>3. Urheber- und Kennzeichenrecht&nbsp;</strong><br />Der Autor ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Bilder, Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihm selbst erstellte Bilder, Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zur&uuml;ckzugreifen.&nbsp;<br />Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte gesch&uuml;tzten Marken- und Warenzeichen unterliegen uneingeschr&auml;nkt den Bestimmungen des jeweils g&uuml;ltigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigent&uuml;mer. Allein aufgrund der blo&szlig;en Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter gesch&uuml;tzt sind!&nbsp;<br />Das Copyright f&uuml;r ver&ouml;ffentlichte, vom Autor selbst erstellte Objekte bleibt allein beim Autor der Seiten. Eine Vervielf&auml;ltigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdr&uuml;ckliche Zustimmung des Autors nicht gestattet.</p>
                                <p><strong>4. Datenschutz</strong><br /><br />Sofern innerhalb des Internetangebotes die M&ouml;glichkeit zur Eingabe pers&ouml;nlicher oder gesch&auml;ftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdr&uuml;cklich freiwilliger Basis. Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist - soweit technisch m&ouml;glich und zumutbar - auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet. Die Nutzung der im Rahmen des Impressums oder vergleichbarer Angaben ver&ouml;ffentlichten Kontaktdaten wie Postanschriften, Telefon- und Faxnummern sowie Emailadressen durch Dritte zur &uuml;bersendung von nicht ausdr&uuml;cklich angeforderten Informationen ist nicht gestattet. Rechtliche Schritte gegen die Versender von sogenannten Spam-Mails bei Verst&ouml;ssen gegen dieses Verbot sind ausdr&uuml;cklich vorbehalten.<br /><br />Weitere Informationen entnehmen Sie bitte der Erkl&auml;rung zum Datenschutz (Privacy Policy).</p>
                                <p><strong>5. Rechtswirksamkeit dieses Haftungsausschlusses&nbsp;</strong><br />Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollst&auml;ndig entsprechen sollten, bleiben die &uuml;brigen Teile des Dokumentes in ihrem Inhalt und ihrer G&uuml;ltigkeit davon unber&uuml;hrt.</p>


                    <p>Trotz sorgf&auml;ltiger inhaltlicher Kontrolle &uuml;bernehmen wir keine Haftung f&uuml;r die Inhalte externer Links. F&uuml;r den Inhalt der verlinkten Seiten sind ausschlie&szlig;lich deren Betreiber verantwortlich.Alle hier verwendeten Namen, Begriffe, Zeichen und Grafiken k&ouml;nnen Marken- oder Warenzeichen im Besitze ihrer rechtlichen Eigent&uuml;mer sein. Die Rechte aller erw&auml;hnten und benutzten Marken- und Warenzeichen liegen ausschlie&szlig;lich bei deren Besitzern.</p>
                </div>
            </div>



            </div>
        </div>
    </div>


@endsection